// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idmttguoujvkypbsxfhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkbXR0Z3VvdWp2a3lwYnN4ZmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjQzNzQsImV4cCI6MjA2Nzk0MDM3NH0.Z-30S52iQdzDr6TJDCFPV9ibSOytTMcmhw4pYnRxqzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});